# Generated by Django 6.0 on 2025-12-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('DAMAGED', 'Damaged'), ('OTHER', 'Other')], max_length=50)),
                ('return_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('replacement_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='orders.orderitem')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement', to='returns.return')),
            ],
            options={
                'ordering': ['-replacement_date'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('ORIGINAL_PAYMENT', 'Original Payment Method'), ('WALLET', 'Wallet'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50)),
                ('refund_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='returns.return')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
