# Generated by Django 6.0 on 2025-12-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('changes', models.JSONField(help_text='JSON field containing list of changes')),
                ('is_major', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='APIEndpointDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('endpoint_path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('protocol', models.CharField(choices=[('REST', 'REST'), ('SOAP', 'SOAP')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(help_text='JSON field for parameters documentation')),
                ('example_request', models.TextField(blank=True)),
                ('example_response', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_name', 'endpoint_path'],
            },
        ),
        migrations.CreateModel(
            name='SetupGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_example', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('installation', 'Installation'), ('configuration', 'Configuration'), ('deployment', 'Deployment'), ('testing', 'Testing')], max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'step_number'],
            },
        ),
    ]
