# Generated by Django 6.0 on 2025-12-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('ORDERS', 'Orders Report'), ('INVENTORY', 'Inventory Report'), ('RETURNS', 'Returns Report'), ('SHIPMENTS', 'Shipments Report'), ('FINANCIAL', 'Financial Report'), ('PERFORMANCE', 'Performance Report')], max_length=20)),
                ('report_name', models.CharField(max_length=255)),
                ('report_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('schedule_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('ORDERS', 'Orders Report'), ('INVENTORY', 'Inventory Report'), ('RETURNS', 'Returns Report'), ('SHIPMENTS', 'Shipments Report'), ('FINANCIAL', 'Financial Report'), ('PERFORMANCE', 'Performance Report')], max_length=20)),
                ('report_name', models.CharField(max_length=255)),
                ('report_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON')], max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('next_run_date', models.DateTimeField()),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.IntegerField(default=0)),
                ('processing_time', models.DecimalField(decimal_places=2, help_text='Processing time in seconds', max_digits=10)),
                ('data_range_start', models.DateTimeField()),
                ('data_range_end', models.DateTimeField()),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.report')),
            ],
        ),
    ]
